#YAML有以下基本规则：
#1、大小写敏感
#2、使用缩进表示层级关系
#3、禁止使用tab缩进，只能使用空格键
#4、缩进长度没有限制，只要元素对齐就表示这些元素属于一个层级。
#5、使用#表示注释
#6、字符串可以不用引号标注
server:
  port: 8063


spring:
  datasource:
#   数据源基本配置
#    url: jdbc:mysql://localhost:3306/goat?Unicode=true&amp;characterEncoding=utf8&useSSL=true
    url: jdbc:mysql://localhost:3306/authority?Unicode=true&amp;characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: goat
    password: jwfl
    driver-class-name: com.mysql.jdbc.Driver

#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true


#  freemarker:
#    charset: utf-8
#    content-type: text/html
#    expose-request-attributes: true   #暴露 request 属性
#    expose-session-attributes: true   #暴露 session 属性
#    expose-spring-macro-helpers: true #暴露 宏 属性

#    suffix: .ftl

#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml









